# Generated by Django 3.0.3 on 2020-03-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Snippets', '0002_auto_20200309_0551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='content',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='snippet',
            old_name='special_instructions',
            new_name='instructions',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='code_quality',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='language',
        ),
        migrations.AddField(
            model_name='snippet',
            name='framework',
            field=models.CharField(choices=[('python', 'Python'), ['django', 'Django']], default='Django', max_length=50),
            preserve_default=False,
        ),
    ]
