# Generated by Django 3.0.3 on 2020-04-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Snippets', '0003_auto_20200322_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='framework',
            field=models.CharField(choices=[('Python', 'Python'), ['Django', 'Django']], max_length=50),
        ),
    ]
